services:
  customeres:
    image: "johanrr/accenture-bank_ms-customers:v0.0.2"
    container_name: accenture-bank_ms-customers
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - accenture-network

  accounts:
    image: "johanrr/accenture-bank_ms-accounts:v0.0.2"
    container_name: accenture-bank_ms-accounts
    ports:
      - "8010:8010"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - accenture-network

networks:
  accenture-network:
    driver: "bridge"