server:
  port: 8010

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: "ms-accounts"
  # SQL DB Config
  #  datasource:
  #    url: jdbc:mysql://localhost:3308/accounts_db
  #    username: root
  #    password: root
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #  sql:
  #    init:
  #      mode: ALWAYS
  # H2 DB config
  datasource:
    url: jdbc:h2:mem:accounts_db
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
  profiles:
    active:
      - "pdn"

  #  rabbitmq:
  #    host: "localhost"
  #    port: 5672
  #    username: "guest"
  #    password: "guest"

  # Config server setup
  config:
    import:
      - "optional:configserver:http://localhost:8071"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true
# Eureka config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
info:
  app:
    name: "ms-accounts"
    description: "accenture bank account services"
    version: "1.0.0"
# Local config
#  config:
#    import:
#      - "application_qa.yml"
#      - "application_pdn.yml"
#  profiles:
#    active:
#      - "default"

##build:
##  version: "v0.0.2"
##
#support:
#  message: "Welcome to bank of Accenture :: Environment local"
#  contactInfo:
#    name: "Johan Rojas"
#    email: "j.rojas.rodriguez@accenture.com"
#  phoneNumbers:
#    - (57)3007193649
#    - (57)3004718713

#  docker run -p 3308:3306 --name accounts_db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=accounts_db -v /Users/j.rojas.rodriguez/docker/my_bank/ms_accounts:/var/lib/mysql -d mysql
#  docker run -p 3307:3306 --name customers_db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=customers_db -v /Users/j.rojas.rodriguez/docker/my_bank/ms_customers:/var/lib/mysql -d mysql