services:
  network-service:
    networks:
      - accenture-network

  ms-base-config:
    extends:
      service: network-service
    deploy:
      resources:
        limits:
          memory: 7000m
    environment:
      SPRING_RABBITMQ_HOST: "rabbitmq"

  ms-base-configserver:
    extends:
      service: ms-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://localhost:8071
