server:
  port: 8000

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: "ms-customers"
  # SQL DB Config
  #  datasource:
  #        u
  #    url: jdbc:mysql://localhost:3307/customers_db
  #    username: root
  #    password: root
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #  sql:
  #    init:
  #      mode: ALWAYS

  # H2 DB Config
  datasource:
    url: jdbc:h2:mem:customers_db
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
  #  rabbitmq:
  #    host: "localhost"
  #    port: 5672
  #    username: "guest"
  #    password: "guest"
  # Config server setup
  config:
    import:
      - "optional:configserver:http://localhost:8071"

  profiles:
    active:
      - "pdn"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

# Eureka config
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka

info:
  app:
    name: "ms-customers"
    description: "accenture bank customers services"
    version: "1.0.0"